Add tests
JincorTech/backend-verify pull request #11
Opened 2017-09-20 15:47 UTC by AlekNS

Add tests for:
* Middlewares
* Services
* Controllers
* Helpers

Fix bugs with parameters validation.

2017-09-20 16:39 UTC, artemii235 requested changes

2017-09-20 16:39 UTC, artemii235 commented on src/controllers/specs/verifiers.spec.ts
> +  it('will fail validation when verificationId not found', (done) => {
Success validation is not tested. Also there are no tests for "remove" method.

2017-09-21 07:22 UTC, hlogeon approved these changes

2017-09-22 08:40 UTC, artemii235 approved these changes

2017-09-22 08:42 UTC, merged