Ready for staging #3 #4 #5
JincorTech/backend-verify pull request #7
Opened 2017-09-19 16:00 UTC by AlekNS

2017-09-19 16:51 UTC, hlogeon requested changes
Configure TSLint as in the other Jincor projects

2017-09-20 07:47 UTC, hlogeon commented
Я думаю, что тесты на сервис\ы верификации тоже неплохо было бы заиметь

2017-09-20 07:49 UTC, hlogeon approved these changes

2017-09-20 11:06 UTC, artemii235 approved these changes

2017-09-20 11:08 UTC, Aleserche approved these changes

2017-09-20 11:38 UTC, merged